var app = new Vue({
    el:'#app',
    data:{
        contacts:[
            {
                name:'Michele',
                avatar:'img/avatar_1.jpg'
            },
            {
                name:'Fabio',
                avatar:'img/avatar_3.jpg'
            },
            {
                name:'Mario',
                avatar:'img/avatar_2.jpg'
            },
            {
                name:'Samuele',
                avatar:'img/avatar_4.jpg'
            },
            {
                name:'Giulia',
                avatar:'img/avatar_io.jpg'
            },
            {
                name:'Lorenzo',
                avatar:'img/avatar_5.jpg'
            },
            {
                name:'Luca',
                avatar:'img/avatar_7.jpg'
            },
            {
                name:'Giovanni',
                avatar:'img/avatar_8.jpg'
            },
            {
                name:'Marco Sebastiani',
                avatar:'img/avatar_3.jpg'
            }

        ]
    }
});